# Generated by Django 5.0.4 on 2024-04-09 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_userprofile_friends_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_message_date', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(to='backend.userprofile')),
                ('messages', models.ManyToManyField(to='backend.message')),
            ],
            options={
                'ordering': ['-last_message_date'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chats',
            field=models.ManyToManyField(blank=True, to='backend.chat'),
        ),
    ]
