# Generated by Django 5.0.4 on 2024-04-11 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_message_chat_userprofile_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='writer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='backend.userprofile'),
            preserve_default=False,
        ),
    ]
