# Generated by Django 5.0.4 on 2024-04-16 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_message_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.chat')),
                ('users', models.ManyToManyField(to='backend.userprofile')),
            ],
        ),
    ]
